package com.example.system.mapper;

import com.example.system.pojo.User_info;
import org.springframework.stereotype.Component;

@Component
public interface User_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insert(User_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insertSelective(User_info record);

    User_info findByName(String name);

    void addUser(String name, String md5Pwd);
}